name: Backend Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests
      run: mvn clean test
    
    - name: Generate coverage report
      run: mvn jacoco:report
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backend-test-results
        path: |
          target/surefire-reports/
          target/site/jacoco/
    
    - name: Build package
      run: mvn package -DskipTests
    
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: target/*.jar