name: Docker Build

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'Dockerfile*'
      - 'docker-compose.yml'
      - '.github/workflows/docker-tests.yml'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: wardkeeper-backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build frontend Docker image (if exists)
      if: hashFiles('frontend/Dockerfile') != ''
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: wardkeeper-frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test docker-compose
      if: hashFiles('docker-compose.yml') != ''
      run: |
        docker-compose config
        docker-compose build
        docker-compose up -d
        sleep 10
        docker-compose ps
        docker-compose logs
        docker-compose down